;; /!\ THIS CODE HAS BEEN WRITTEN BY GOOGLE LLM CALLED GEMINI 3 THINKING
;; /!\ THIS HAS BEEN GENERATED BY AI
;; /!\ USED FOR COMPARISON ONLY

;;; Day 3: Lobby - Battery Joltage Problem
;;; R5RS Scheme Solution

(define (char-digit? c)
  (and (char>=? c #\0) (char<=? c #\9)))

(define (char->digit c)
  (- (char->integer c) (char->integer #\0)))

;;; Converts a string into a list of integers, ignoring non-digits
(define (string->digit-list s)
  (let loop ((i 0) (acc '()))
    (if (= i (string-length s))
        (reverse acc)
        (let ((c (string-ref s i)))
          (if (char-digit? c)
              (loop (+ i 1) (cons (char->digit c) acc))
              (loop (+ i 1) acc))))))

;;; Finds the maximum 2-digit joltage (10*d1 + d2) in a list of digits
;;; where d1 comes before d2 in the list.
(define (solve-bank digits)
  (let loop-outer ((lst digits) (max-jolt 0))
    (if (null? lst)
        max-jolt
        (let ((d1 (car lst))
              (rest (cdr lst)))
          ;; Inner loop: pair d1 with every subsequent digit d2
          (let loop-inner ((remaining rest) (current-max max-jolt))
            (if (null? remaining)
                ;; Move to the next digit in the outer loop
                (loop-outer rest current-max)
                (let* ((d2 (car remaining))
                       (val (+ (* d1 10) d2)))
                  (loop-inner (cdr remaining) (max current-max val)))))))))

;;; Helper to read a full line from stdin
(define (read-line)
  (let loop ((chars '()))
    (let ((c (read-char)))
      (cond 
        ((eof-object? c) 
         (if (null? chars) c (list->string (reverse chars))))
        ((char=? c #\newline) 
         (list->string (reverse chars)))
        (else 
         (loop (cons c chars)))))))

;;; Main execution loop
(define (main)
  (let loop ((total-output 0))
    (let ((line (read-line)))
      (if (eof-object? line)
          (begin
            (display "Total Output Joltage: ")
            (display total-output)
            (newline))
          (let ((digits (string->digit-list line)))
            (if (null? digits)
                (loop total-output) ;; Skip empty lines
                (loop (+ total-output (solve-bank digits)))))))))

;;; Run the program
(main)
